//===- IRDLSSAAttributes.td - IRDL Attributes --------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file declares the attributes IRDL-SSA uses.
//
//===----------------------------------------------------------------------===//

#ifndef DYN_DIALECT_IRDL_SSA_IR_IRDLSSAATTRIBUTES
#define DYN_DIALECT_IRDL_SSA_IR_IRDLSSAATTRIBUTES


#endif // DYN_DIALECT_IRDL_SSA_IR_IRDLSSAATTRIBUTES